# Introduction to Python:- Numpy (DataCamp.com)

In [1]:
height = [1.73, 1.68, 1.71, 1.89, 1.79]
height

[1.73, 1.68, 1.71, 1.89, 1.79]

In [2]:
weight = [65.4, 59.2, 63.6, 88.4, 68.7]
weight

[65.4, 59.2, 63.6, 88.4, 68.7]

In [3]:
weight /height ** 2

TypeError: unsupported operand type(s) for ** or pow(): 'list' and 'int'

In [4]:
import numpy as np

In [6]:
np_height = np.array(height)
np_height

array([1.73, 1.68, 1.71, 1.89, 1.79])

In [7]:
np_weight = np.array(weight)
np_weight

array([65.4, 59.2, 63.6, 88.4, 68.7])

### Bmi = Body Mass Index

In [8]:
bmi = np_weight / np_height ** 2
bmi

array([21.85171573, 20.97505669, 21.75028214, 24.7473475 , 21.44127836])

## Note:- Numpy arrays contain only one type

In [9]:
np.array([1.0,"is",True])

array(['1.0', 'is', 'True'], dtype='<U32')

In [10]:
python_list = [1,2,3]
numpy_array = np.array([1,2,3])

In [11]:
python_list + python_list

[1, 2, 3, 1, 2, 3]

In [12]:
numpy_array + numpy_array

array([2, 4, 6])

In [13]:
bmi

array([21.85171573, 20.97505669, 21.75028214, 24.7473475 , 21.44127836])

In [14]:
bmi[1]

20.97505668934241

In [15]:
bmi >23

array([False, False, False,  True, False])

In [16]:
bmi[bmi > 23]

array([24.7473475])

# Exercise:- Your First NumPy Array

In this chapter, we're going to dive into the world of baseball. Along the way, you'll get comfortable with the basics of **numpy**, a powerful package to do data science.

A list **baseball** has already been defined in the Python script, representing the height of some baseball players in centimeters. Can you add some code here and there to create a **numpy** array from it?

In [17]:
# Create list baseball
baseball = [180, 215, 210, 210, 188, 176, 209, 200]

# Import the numpy package as np
import numpy as np

# Create a numpy array from baseball: np_baseball
np_baseball = np.array(baseball)

# Print out type of np_baseball
print(type(np_baseball))

<class 'numpy.ndarray'>


# Exercise:- Baseball players' height
You are a huge baseball fan. You decide to call the MLB (Major League Baseball) and ask around for some more statistics on the height of the main players. They pass along data on more than a thousand players, which is stored as a regular Python list: **height_in**. The height is expressed in inches. Can you make a **numpy** array out of it and convert the units to meters?

**height_in** is already available and the **numpy** package is loaded, so you can start straight away (Source: stat.ucla.edu).

In [ ]:
# height is available as a regular list

# Import numpy
import numpy as np

# Create a numpy array from height_in: np_height_in
np_height_in = np.array(height_in)

# Print out np_height_in
print(np_height_in)

# Convert np_height_in to m: np_height_m
np_height_m = np_height_in*0.0254

# Print np_height_m
print(np_height_m)

# Note:- convert inches to meters:-
        1 inch = 0.0254 meter
        
## pounds to kilograms:-
        1 pound = 0.453592
        
## BMI:-  weight(kg)2  /  height(m)**2

# Exercise:- Baseball player's BMI
The MLB also offers to let you analyze their weight data. Again, both are available as regular Python lists: **height_in** and **weight_lb**. **height_in** is in inches and **weight_lb** is in pounds.

It's now possible to calculate the BMI of each baseball player. Python code to convert **height_in** to a **numpy** array with the correct units is already available in the workspace. Follow the instructions step by step and finish the game!

In [ ]:
# height and weight are available as regular lists

# Import numpy
import numpy as np

# Create array from height_in with metric units: np_height_m
np_height_m = np.array(height_in) * 0.0254

# Create array from weight_lb with metric units: np_weight_kg
np_weight_kg = np.array(weight_lb)*0.453592

# Calculate the BMI: bmi
bmi  = np_weight_kg/(np_height_m)**2

# Print out bmi
print(bmi)

# Exercise:- Lightweight baseball players
To subset both regular Python lists and **numpyv arrays, you can use square brackets:

        x = [4 , 9 , 6, 3, 1]
        x[1]
        import numpy as np
        y = np.array(x)
        y[1]
For **numpy** specifically, you can also use boolean **numpy** arrays:

        high = y > 5
        y[high]
The code that calculates the BMI of all baseball players is already included. Follow the instructions and reveal interesting things from the data!

### Instruction:- 
Create a boolean **numpy** array: the element of the array should be **True** if the corresponding baseball player's BMI is below 21. You can use the **<** operator for this. Name the array **light**.

Print the array light.

Print out a **numpy** array with the BMIs of all **baseball** players whose BMI is below 21. Use **light** inside square brackets to do a selection on the **bmi** array.

In [ ]:
# height and weight are available as a regular lists

# Import numpy
import numpy as np

# Calculate the BMI: bmi
np_height_m = np.array(height_in) * 0.0254
np_weight_kg = np.array(weight_lb) * 0.453592
bmi = np_weight_kg / np_height_m ** 2

# Create the light array
light = bmi<21

# Print out light
print(light)

# Print out BMIs of all baseball players whose BMI is below 21
print(bmi[bmi<21])

# NumPy Side Effects
As Hugo explained before, **numpy** is great for doing vector arithmetic. If you compare its functionality with regular Python lists, however, some things have changed.

First of all, **numpy** arrays cannot contain elements with different types. If you try to build such a list, some of the elements' types are changed to end up with a homogeneous list. This is known as type coercion.

Second, the typical arithmetic operators, such as **+, -, * and /** have a different meaning for regular Python lists and ****numpy** arrays.

Have a look at this line of code:

        np.array([True, 1, 2]) + np.array([3, 4, False])
        
Can you tell which code chunk builds the exact same Python object? The **numpy** package is already imported as **np**, so you can start experimenting in the IPython Shell straight away!

# Instructions:-
Possible Answers :=

        a. np.array([True, 1, 2, 3, 4, False])
        b. np.array([4, 3, 0]) + np.array([0, 2, 2])
        c. np.array([1, 1, 2]) + np.array([3, 4, -1])
        d. np.array([0, 1, 2, 3, 4, 5])

In [ ]:
np.array([4, 3, 0]) + np.array([0, 2, 2])

# Exercise:- Subsetting NumPy Arrays
You've seen it with your own eyes: Python lists and **numpy**arrays sometimes behave differently. Luckily, there are still certainties in this world. For example, subsetting (using the square bracket notation on lists or arrays) works exactly the same. To see this for yourself, try the following lines of code in the IPython Shell:

        x = ["a", "b", "c"]
        x[1]

        np_x = np.array(x)
        np_x[1]
        
The script on the right already contains code that imports numpy as **np**, and stores both the height and weight of the MLB players as **numpy** arrays.

### Instructions:-
* Subset **np_weight_lb** by printing out the element at index 50.
* Print out a sub-array of **np_height_in** that contains the elements at index 100 up to and including index 110.

In [ ]:
# height and weight are available as a regular lists

# Import numpy
import numpy as np

# Store weight and height lists as numpy arrays
np_weight_lb = np.array(weight_lb)
np_height_in = np.array(height_in)

# Print out the weight at index 50
print(np_weight_lb[50])

# Print out sub-array of np_height_in: index 100 up to and including index 110
print(np_height_in[100:111])

# 2D Numpy Arrays:-
Type of numpy arrays

In [1]:
import numpy as np
np_height = np.array([1.73,1.68,1.71,1.89, 1.79])
np_weight = np.array([65.4, 59.2, 63.6, 88.4, 68.7])

In [2]:
type(np_height)

numpy.ndarray

In [3]:
print(type(np_weight))

<class 'numpy.ndarray'>


In [5]:
np_2d = np.array([[1.73,1.68,1.71,1.89, 1.79],
                 [65.4, 59.2, 63.6, 88.4, 68.7]])
np_2d

array([[ 1.73,  1.68,  1.71,  1.89,  1.79],
       [65.4 , 59.2 , 63.6 , 88.4 , 68.7 ]])

In [6]:
np_2d.shape

(2, 5)

In [7]:
np.array([[1.73,1.68,1.71,1.89, 1.79],
                 [65.4, 59.2, 63.6, 88.4, '68.7']])

array([['1.73', '1.68', '1.71', '1.89', '1.79'],
       ['65.4', '59.2', '63.6', '88.4', '68.7']], dtype='<U32')

## Note:- If you change one float to be string, all the array elements will be coerced to strings.

In [8]:
np_2d[0]

array([1.73, 1.68, 1.71, 1.89, 1.79])

In [9]:
np_2d[0][3]

1.89

In [10]:
np_2d[0,3]

1.89

# Exercise:-Your First 2D NumPy Array
Before working on the actual MLB data, let's try to create a **2D numpy** array from a small list of lists.

In this exercise, **baseball** is a list of lists. The main list contains 4 elements. Each of these elements is a list containing the height and the weight of 4 **baseball** players, in this order. baseball is already coded for you in the script.
# Instructions:-
Use **np.array()** to create a **2D numpy array** from baseball. Name it **np_baseball**.

Print out the type of **np_baseball**.
Print out the shape attribute of **np_baseball**. Use **np_baseball.shape**.

In [ ]:
# Create baseball, a list of lists
baseball = [[180, 78.4],
            [215, 102.7],
            [210, 98.5],
            [188, 75.2]]

# Import numpy
import numpy as np

# Create a 2D numpy array from baseball: np_baseball
np_baseball = np.array(baseball)

# Print out the type of np_baseball
print(type(np_baseball))

# Print out the shape of np_baseball
print(np_baseball.shape)

# Exercise:- Baseball data in 2D form
You have another look at the MLB data and realize that it makes more sense to restructure all this information in a 2D **numpy** array. This array should have 1015 rows, corresponding to the 1015 baseball players you have information on, and 2 columns (for height and weight).

The MLB was, again, very helpful and passed you the data in a different structure, a Python list of lists. In this list of lists, each sublist represents the height and weight of a single baseball player. The name of this embedded list is **baseball**.

Can you store the data as a 2D array to unlock **numpy**'s extra functionality?
# Instructions:- 
Use **np.array()** to create a 2D numpy array from **baseball**. Name it **np_baseball**.

Print out the **shape** attribute of **np_baseball**.

In [ ]:
# baseball is available as a regular list of lists = 

# Import numpy package
import numpy as np

# Create a 2D numpy array from baseball: np_baseball
np_baseball = np.array(baseball)

# Print out the shape of np_baseball
print(np_baseball.shape)

# Exercise:- Subsetting 2D NumPy Arrays
If your 2D numpy array has a regular structure, i.e. each row and column has a fixed number of values, complicated ways of subsetting become very easy. Have a look at the code below where the elements "a" and "c" are extracted from a list of lists.

        # regular list of lists
        x = [["a", "b"], ["c", "d"]]
        [x[0][0], x[1][0]]

        # numpy
        import numpy as np
        np_x = np.array(x)
        np_x[:,0]
        
For regular Python lists, this is a real pain. For 2D numpy arrays, however, it's pretty intuitive! The indexes before the comma refer to the rows, while those after the comma refer to the columns. The : is for slicing; in this example, it tells Python to include all rows.

The code that converts the pre-loaded baseball list to a 2D numpy array is already in the script. The first column contains the players' height in inches and the second column holds player weight, in pounds. Add some lines to make the correct selections. Remember that in Python, the first element is at index 0!

# Instructions:-
* Print out the 50th row of np_baseball.
* Make a new variable, np_weight_lb, containing the entire second column of np_baseball.
* Select the height (first column) of the 124th baseball player in np_baseball and print it out.

In [ ]:
# baseball is available as a regular list of lists

# Import numpy package
import numpy as np

# Create np_baseball (2 cols)
np_baseball = np.array(baseball)

# Print out the 50th row of np_baseball
print(np_baseball[49,:])

# Select the entire second column of np_baseball: np_weight_lb
np_weight_lb = np_baseball[:,1]

# Print out height of 124th player
print(np_baseball[123][0])

# Exercise:- 2D Arithmetic
Remember how you calculated the Body Mass Index for all baseball players? numpy was able to perform all calculations element-wise (i.e. element by element). For 2D numpy arrays this isn't any different! You can combine matrices with single numbers, with vectors, and with other matrices.

Execute the code below in the IPython shell and see if you understand:

        import numpy as np
        np_mat = np.array([[1, 2],
                           [3, 4],
                           [5, 6]])
        np_mat * 2
        np_mat + np.array([10, 10])
        np_mat + np_mat
np_baseball is coded for you; it's again a 2D numpy array with 3 columns representing height (in inches), weight (in pounds) and age (in years).

# Instructions:-
* You managed to get hold of the changes in height, weight and age of all baseball players. It is available as a 2D numpy array, updated. Add np_baseball and updated and print out the result.
* You want to convert the units of height and weight to metric (meters and kilograms respectively). As a first step, create a numpy array with three values: 0.0254, 0.453592 and 1. Name this array conversion.
* Multiply np_baseball with conversion and print out the result.

In [ ]:
# baseball is available as a regular list of lists
# updated is available as 2D numpy array

# Import numpy package
import numpy as np

# Create np_baseball (3 cols)
np_baseball = np.array(baseball)

# Print out addition of np_baseball and updated
print(np_baseball + updated)

# Create numpy array: conversion
conversion = np.array([0.0254, 0.453592, 1])

# Print out product of np_baseball and conversion
print(np_baseball * conversion)

# Numpy:- Basic Statistics

In [11]:
#mean:- average Value
np.mean(np_weight)

69.06

In [13]:
#median:- first sort matrix or array and return middle value
np.median(np_weight)

65.4

In [14]:
#corrcoef:- The relationship between the correlation coefficient matrix
np.corrcoef(np_weight)

1.0

In [15]:
#std:- Standard deviation
np.std(np_weight)

10.14487062509917

## Generate data

Arguments for np.random.noraml()
*    distribution mean
*    distribution standard deviation
*    number of samples


In [26]:
height = np.round(np.random.normal(1.75,0.20,5000),2)
weight = np.round(np.random.normal(60.32, 15, 5000),2)

In [27]:
height

array([1.58, 1.66, 1.91, ..., 1.62, 1.91, 1.87])

In [28]:
print(type(height))

<class 'numpy.ndarray'>


In [29]:
print(height)

[1.58 1.66 1.91 ... 1.62 1.91 1.87]


In [32]:
np_city = np.column_stack((height, weight))

In [33]:
np_city

array([[ 1.58, 56.65],
       [ 1.66, 34.76],
       [ 1.91, 71.02],
       ...,
       [ 1.62, 49.2 ],
       [ 1.91, 63.76],
       [ 1.87, 36.99]])

In [34]:
np_city.shape

(5000, 2)

# Exercise:- Average versus median
You now know how to use numpy functions to get a better feeling for your data. It basically comes down to importing numpy and then calling several simple functions on the numpy arrays:

        import numpy as np
        x = [1, 4, 8, 10, 12]
        np.mean(x)
        np.median(x)
The baseball data is available as a 2D numpy array with 3 columns (height, weight, age) and 1015 rows. The name of this numpy array is np_baseball. After restructuring the data, however, you notice that some height values are abnormally high. Follow the instructions and discover which summary statistic is best suited if you're dealing with so-called outliers.

# Instructions:-
* Create numpy array np_height_in that is equal to first column of np_baseball.
* Print out the mean of np_height_in.
* Print out the median of np_height_in.

In [ ]:
# np_baseball is available

# Import numpy
import numpy as np

# Create np_height_in from np_baseball
np_height_in = np_baseball[:,0]
# Print out the mean of np_height_in
print(np.mean(np_height_in))

# Print out the median of np_height_in
print(np.median(np_height_in))

# Exercise:- Explore the baseball data
Because the mean and median are so far apart, you decide to complain to the MLB. They find the error and send the corrected data over to you. It's again available as a 2D Numpy array np_baseball, with three columns.

The Python script on the right already includes code to print out informative messages with the different summary statistics. Can you finish the job?

## Instructions:-
* The code to print out the mean height is already included. Complete the code for the median height. Replace None with the correct code.
* Use np.std() on the first column of np_baseball to calculate stddev. Replace None with the correct code.
* Do big players tend to be heavier? Use np.corrcoef() to store the correlation between the first and second column of np_baseball in corr. Replace None with the correct code.

In [ ]:
# np_baseball is available

# Import numpy
import numpy as np

# Print mean height (first column)
avg = np.mean(np_baseball[:,0])
print("Average: " + str(avg))

# Print median height. Replace 'None'
med = np.median(np_baseball[:,0])
print("Median: " + str(med))

# Print out the standard deviation on height. Replace 'None'
stddev = np.std(np_baseball[:,0])
print("Standard Deviation: " + str(stddev))

# Print out correlation between first and second column. Replace 'None'
corr = np.corrcoef(np_baseball[:,0],np_baseball[:,1])
print("Correlation: " + str(corr))

# Exercise:- Blend it all together
In the last few exercises you've learned everything there is to know about heights and weights of baseball players. Now it's time to dive into another sport: soccer.

You've contacted FIFA for some data and they handed you two lists. The lists are the following:

        positions = ['GK', 'M', 'A', 'D', ...]
        heights = [191, 184, 185, 180, ...]
Each element in the lists corresponds to a player. The first list, positions, contains strings representing each player's position. The possible positions are: 'GK' (goalkeeper), 'M' (midfield), 'A' (attack) and 'D' (defense). The second list, heights, contains integers representing the height of the player in cm. The first player in the lists is a goalkeeper and is pretty tall (191 cm).

You're fairly confident that the median height of goalkeepers is higher than that of other players on the soccer field. Some of your friends don't believe you, so you are determined to show them using the data you received from FIFA and your newly acquired Python skills.

### Instructions:-
* Convert heights and positions, which are regular lists, to numpy arrays. Call them np_heights and np_positions.
* Extract all the heights of the goalkeepers. You can use a little trick here: use np_positions == 'GK' as an index for np_heights. Assign the result to gk_heights.
* Extract all the heights of all the other players. This time use np_positions != 'GK' as an index for np_heights. Assign the result to other_heights.
* Print out the median height of the goalkeepers using np.median(). Replace None with the correct code.
* Do the same for the other players. Print out their median height. Replace None with the correct code.

In [ ]:
# heights and positions are available as lists

# Import numpy
import numpy as np

# Convert positions and heights to numpy arrays: np_positions, np_heights
np_positions = np.array(positions)
np_heights = np.array(heights)

# Heights of the goalkeepers: gk_heights
gk_heights = np_heights[np_positions == 'GK']

# Heights of the other players: other_heights
other_heights = np_heights[np_positions != 'GK']

# Print out the median height of goalkeepers. Replace 'None'
print("Median height of goalkeepers: " + str(np.median(gk_heights)))

# Print out the median height of other players. Replace 'None'
print("Median height of other players: " + str(np.median(other_heights)))