In [1]:
height = [1.73, 1.68, 1.71, 1.89, 1.79]
height

[1.73, 1.68, 1.71, 1.89, 1.79]

In [2]:
weight = [65.4, 59.2, 63.6, 88.4, 68.7]
weight

[65.4, 59.2, 63.6, 88.4, 68.7]

In [3]:
weight /height ** 2

TypeError: unsupported operand type(s) for ** or pow(): 'list' and 'int'

In [4]:
import numpy as np

In [6]:
np_height = np.array(height)
np_height

array([1.73, 1.68, 1.71, 1.89, 1.79])

In [7]:
np_weight = np.array(weight)
np_weight

array([65.4, 59.2, 63.6, 88.4, 68.7])

### Bmi = Body Mass Index

In [8]:
bmi = np_weight / np_height ** 2
bmi

array([21.85171573, 20.97505669, 21.75028214, 24.7473475 , 21.44127836])

## Note:- Numpy arrays contain only one type

In [9]:
np.array([1.0,"is",True])

array(['1.0', 'is', 'True'], dtype='<U32')

In [10]:
python_list = [1,2,3]
numpy_array = np.array([1,2,3])

In [11]:
python_list + python_list

[1, 2, 3, 1, 2, 3]

In [12]:
numpy_array + numpy_array

array([2, 4, 6])

In [13]:
bmi

array([21.85171573, 20.97505669, 21.75028214, 24.7473475 , 21.44127836])

In [14]:
bmi[1]

20.97505668934241

In [15]:
bmi >23

array([False, False, False,  True, False])

In [16]:
bmi[bmi > 23]

array([24.7473475])

# Exercise:- Your First NumPy Array

In this chapter, we're going to dive into the world of baseball. Along the way, you'll get comfortable with the basics of **numpy**, a powerful package to do data science.

A list **baseball** has already been defined in the Python script, representing the height of some baseball players in centimeters. Can you add some code here and there to create a **numpy** array from it?

In [17]:
# Create list baseball
baseball = [180, 215, 210, 210, 188, 176, 209, 200]

# Import the numpy package as np
import numpy as np

# Create a numpy array from baseball: np_baseball
np_baseball = np.array(baseball)

# Print out type of np_baseball
print(type(np_baseball))

<class 'numpy.ndarray'>


# Exercise:- Baseball players' height
You are a huge baseball fan. You decide to call the MLB (Major League Baseball) and ask around for some more statistics on the height of the main players. They pass along data on more than a thousand players, which is stored as a regular Python list: **height_in**. The height is expressed in inches. Can you make a **numpy** array out of it and convert the units to meters?

**height_in** is already available and the **numpy** package is loaded, so you can start straight away (Source: stat.ucla.edu).

In [ ]:
# height is available as a regular list

# Import numpy
import numpy as np

# Create a numpy array from height_in: np_height_in
np_height_in = np.array(height_in)

# Print out np_height_in
print(np_height_in)

# Convert np_height_in to m: np_height_m
np_height_m = np_height_in*0.0254

# Print np_height_m
print(np_height_m)

# Note:- convert inches to meters:-
        1 inch = 0.0254 meter
        
## pounds to kilograms:-
        1 pound = 0.453592
        
## BMI:-  weight(kg)2  /  height(m)**2

# Exercise:- Baseball player's BMI
The MLB also offers to let you analyze their weight data. Again, both are available as regular Python lists: **height_in** and **weight_lb**. **height_in** is in inches and **weight_lb** is in pounds.

It's now possible to calculate the BMI of each baseball player. Python code to convert **height_in** to a **numpy** array with the correct units is already available in the workspace. Follow the instructions step by step and finish the game!

In [ ]:
# height and weight are available as regular lists

# Import numpy
import numpy as np

# Create array from height_in with metric units: np_height_m
np_height_m = np.array(height_in) * 0.0254

# Create array from weight_lb with metric units: np_weight_kg
np_weight_kg = np.array(weight_lb)*0.453592

# Calculate the BMI: bmi
bmi  = np_weight_kg/(np_height_m)**2

# Print out bmi
print(bmi)